/** Training Ledger design reminder: progress charts are quiet measurement tools; the important number always stays readable. */
import { FormEvent, useMemo, useRef, useState } from "react";
import { Activity, Download, FileChartColumn, FileSpreadsheet, FileText, Scale, TrendingUp } from "lucide-react";
import { Button } from "@/components/ui/button";
import { AppShell, EmptyLedger, PageHeading } from "@/components/AppShell";
import { toDisplayWeight, toGrams } from "@/lib/workout-types";
import { useGym } from "@/contexts/GymContext";
import { describeWorkout, downloadProgressChart, downloadTrainingData, downloadWorkbook, weeklyDescriptions } from "@/lib/export-data";

const localToday = () => { const now = new Date(); now.setMinutes(now.getMinutes() - now.getTimezoneOffset()); return now.toISOString().slice(0, 10); };

export default function Progress() {
  const { state, addBodyWeight } = useGym(); const [weight, setWeight] = useState(""); const [date, setDate] = useState(localToday); const chartRef = useRef<SVGSVGElement>(null);
  const sorted = state.bodyWeight.slice().sort((a, b) => a.date.localeCompare(b.date)); const latest = sorted.at(-1); const first = sorted[0]; const change = latest && first ? latest.weightGrams - first.weightGrams : 0;
  const chart = useMemo(() => { if (sorted.length < 2) return ""; const values = sorted.map((item) => item.weightGrams); const min = Math.min(...values) - 500; const max = Math.max(...values) + 500; return sorted.map((item, index) => `${(index / (sorted.length - 1)) * 100},${100 - ((item.weightGrams - min) / (max - min || 1)) * 100}`).join(" "); }, [sorted]);
  const save = async (event: FormEvent) => { event.preventDefault(); const parsed = Number(weight); if (parsed > 0) { await addBodyWeight(toGrams(parsed, state.profile.unitSystem), date); setWeight(""); } };
  const completed = state.sessions.filter((session) => session.status === "completed").slice().sort((a, b) => b.date.localeCompare(a.date)); const weeks = weeklyDescriptions(state);
  return <AppShell><PageHeading index="06" eyebrow="Progress" title="Measure the trend." /><p className="page-intro">A light-touch body-weight log for the signals that matter outside a single session.</p>
    <section className="progress-top"><div className="weight-stat"><span><Scale size={16}/> LATEST WEIGHT</span><strong>{latest ? toDisplayWeight(latest.weightGrams, state.profile.unitSystem) : "—"}</strong><small>{latest ? new Date(`${latest.date}T12:00:00`).toLocaleDateString("en", { month: "long", day: "numeric" }) : "No entry yet"}</small></div><div className="weight-stat"><span><TrendingUp size={16}/> CHANGE</span><strong className={change > 0 ? "positive" : change < 0 ? "negative" : ""}>{first && latest ? `${change > 0 ? "+" : ""}${toDisplayWeight(change, state.profile.unitSystem)}` : "—"}</strong><small>across logged entries</small></div></section>
    <section className="weight-chart"><div className="section-topline"><p className="ledger-index">BODY WEIGHT / TREND</p><span>{sorted.length} entries</span></div>{chart ? <svg ref={chartRef} viewBox="0 0 100 100" preserveAspectRatio="none" aria-label="Body weight trend"><defs><linearGradient id="ledgerFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#3e6d57" stopOpacity=".2"/><stop offset="100%" stopColor="#3e6d57" stopOpacity="0"/></linearGradient></defs><polyline points={`0,100 ${chart} 100,100`} fill="url(#ledgerFill)" stroke="none"/><polyline points={chart} fill="none" stroke="#3e6d57" strokeWidth="2" vectorEffect="non-scaling-stroke"/></svg> : <EmptyLedger title="Trend starts with a second entry" body="Log today’s body weight to create the first point." />}</section>
    <form className="weight-entry" onSubmit={save}><div><Activity size={19}/><strong>Log body weight</strong></div><label className="field-label">DATE<input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><label className="field-label">WEIGHT / {state.profile.unitSystem.toUpperCase()}<input inputMode="decimal" value={weight} onChange={(event) => setWeight(event.target.value)} placeholder="0.0" /></label><Button className="ledger-button" type="submit">Save measurement</Button></form>
    <section className="export-sheet"><div><p className="ledger-index">LOCAL / DOWNLOADS</p><h2>Keep your record.</h2><p>Everything downloads directly to this device: detailed workout days, weekly summaries, sets, body-weight data, and the chart.</p></div><div className="export-actions"><Button variant="outline" onClick={() => downloadWorkbook(state)}><FileSpreadsheet size={16}/> Download Excel</Button><Button variant="outline" onClick={() => downloadProgressChart(chartRef.current)} disabled={!chart}><FileChartColumn size={16}/> Download chart</Button><Button variant="outline" onClick={() => downloadTrainingData(state)}><Download size={16}/> Download data</Button></div></section>
    <section className="progress-narratives"><div className="section-topline"><p className="ledger-index">ACTUAL WORK / DESCRIPTIONS</p><span>{completed.length} completed</span></div>{completed.length ? <div className="narrative-list">{completed.slice(0, 8).map((session) => <article key={session.id}><FileText size={16}/><p>{describeWorkout(session)}</p></article>)}</div> : <EmptyLedger title="Descriptions begin with your first completed workout" body="Finish a session and this page will explain the exercises, sets, reps, and volume you recorded." />}</section>
    <section className="weekly-narratives"><div className="section-topline"><p className="ledger-index">WEEKLY / SUMMARY</p><span>{weeks.length} weeks</span></div>{weeks.length ? weeks.map((week) => <article key={week.week}><span className="set-stamp">WK</span><p>{week.description}</p></article>) : <p className="low-emphasis">Your first completed workout will create a detailed weekly summary here.</p>}</section>
  </AppShell>;
}
